version: "3"

services:
  db:
    image: postgres:14.11
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    command: gunicorn --bind 0.0.0.0:8002 core.wsgi:application

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - api
    ports:
      - "8080:8080"
      - "443:443"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - /etc/letsencrypt/:/etc/letsencrypt/

  
  elasticsearch:
    image: elasticsearch:7.17.20
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

volumes:
  db:
  static_volume:
  media_volume:
  esdata:
