# Generated by Django 4.2 on 2024-04-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('New', 'New')], default='New', max_length=20),
        ),
    ]
