# Generated by Django 4.2 on 2024-04-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_order_orderitem_order_product_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='default_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/defaults/'),
        ),
    ]
