# Generated by Django 4.2 on 2024-04-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_foodcategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/promotion_image/')),
                ('link', models.URLField(blank=True)),
            ],
        ),
    ]
