# Generated by Django 4.2 on 2024-04-21 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductBrandImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='media/product_brand/')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_arrived',
        ),
        migrations.AddField(
            model_name='brand',
            name='images',
            field=models.ImageField(default=1, upload_to='media/brand/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BrandImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='media/brand/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_images', to='products.brand')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='brand_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brand_image', to='products.productbrandimage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='extra_info',
            field=models.ManyToManyField(blank=True, to='products.extrainfo'),
        ),
    ]
