# Generated by Django 4.2 on 2024-04-23 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_extra_info_product_arrived_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/food_category/')),
            ],
        ),
        migrations.RemoveField(
            model_name='brandimage',
            name='brand',
        ),
        migrations.DeleteModel(
            name='ExtraInfo',
        ),
        migrations.RemoveField(
            model_name='foodcategory',
            name='catalog',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='images',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand_image',
        ),
        migrations.DeleteModel(
            name='BrandImage',
        ),
        migrations.DeleteModel(
            name='ProductBrandImage',
        ),
        migrations.AlterField(
            model_name='product',
            name='food_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category'),
        ),
        migrations.DeleteModel(
            name='FoodCategory',
        ),
    ]
