# Generated by Django 4.2 on 2024-04-23 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_remove_brandimage_brand_delete_extrainfo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='food_category',
            new_name='category',
        ),
    ]
