# Generated by Django 4.2 on 2024-04-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_images_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extra_info',
            field=models.TextField(default='hahaha'),
            preserve_default=False,
        ),
    ]
