# Generated by Django 4.2 on 2024-04-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_subcategory_delete_catalog_alter_product_extra_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='name',
            field=models.CharField(default='Islam', max_length=150),
            preserve_default=False,
        ),
    ]
