# Generated by Django 4.2 on 2024-04-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_customerreview_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
